# Generated by Django 4.2.7 on 2023-11-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorModel',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('contact_details', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('vendor_code', models.AutoField(primary_key=True, serialize=False)),
                ('on_time_delivery_rate', models.FloatField()),
                ('average_response_time', models.FloatField()),
                ('fullfillment_rate', models.FloatField()),
            ],
        ),
    ]
