# Generated by Django 4.2.7 on 2023-11-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorX', '0003_performancemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendormodel',
            name='average_response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendormodel',
            name='fullfillment_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendormodel',
            name='on_time_delivery_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
